title: Andrew's Blog
email: andrewlu@college.harvard.edu
description: >- HCS Bootcamp 4 Project
baseurl: "/blog"
url: http://andrewlu00.com
twitter_username: N/A
github_username:  andrewlu00

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
